### ISSUE TITLE
datetime_convert.cc date string issue

### ISSUE THREAD

**Issue by snowsurfer101** [r3ub/OpenSourceProject#11]
On line 12, developer tried to initialize a string and there is double quotes on one side and single quotes on the other side.

Steps to Reproduce

Expected to compile.

Compiler error.

![image](https://user-images.githubusercontent.com/112723307/226640901-d65c705a-6bdf-48f9-a54d-b187f1d23243.png)

Operating System: Windows 11
Browser: CLion
Version: unknown

Use double quotations at the end instead of single quotes.

Low priority.

Reproducibility: always

High impact, code won't even compile.

https://github.com/r3ub/OpenSourceProject/blob/main/programming%20files/datetime_convert.cc

**Comment by dakotasmith13** [comment]
Fixed.
