### ISSUE TITLE
sum_even_fibonacci.cc bugs

### ISSUE THREAD

**Issue by astute404** [r3ub/OpenSourceProject#12]
Description: The code does not compile

Steps to Reproduce: 
1. Try to build the code

Expected behavior: Code should build

Actual behavior: Code does not build

Screenshot: 
![image](https://user-images.githubusercontent.com/113051585/226642051-71ad384d-12e6-4cab-9900-e71f0e54659f.png)

OS: Windows 10

Possible solution: Resolve the error in the code presented by a compiler

Priority: High, code does not work at all right now

Reproducibility: Always

Impact: High

**Comment by r3ub** [comment]
Fixed!
