### ISSUE TITLE
Array out of bounds Bug in remove_duplicates.java

### ISSUE THREAD

**Issue by dakotasmith13** [r3ub/OpenSourceProject#15]
Description: In for loop in removeDuplicates, i <= arr.size(), should be i < arr.size().

Steps to Reproduce: run program, will get compiler error with index out of bounds
Expected Behavior: should display original array, removed values, and updated array.

Actual Behavior: compiler error with index out of bounds

Additional Information

Operating System: Windows 10
Browser: Chrome
Version:111.0.5563.65
Any other relevant information
Possible Solution: change i <= arr.size() to i < arr.size()

Priority How critical is this issue/bug? Low, medium, or high priority? High

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random? Always

Impact What is the impact of this issue/bug? Low, medium, or high? High

**Comment by snowsurfer101** [comment]
I fixed it!
