### ISSUE TITLE
Another bug in sum_even_fibonacci.cc

### ISSUE THREAD

**Issue by astute404** [r3ub/OpenSourceProject#16]
Description: The code does not compile

Steps to Reproduce:
1. Try to build the code

Expected behavior: The code compiles

Actual behavior: The code does not compile

Screenshot: 
![image](https://user-images.githubusercontent.com/113051585/226643427-8df6cad5-4864-4cbf-84f9-ba11c4061932.png)

OS: Windows 10

Possible solution: Resolve the error given by the compiler

Priority: High, the code does not work at all

Reproducibility: Always

Impact: High

**Comment by r3ub** [comment]
Fixed!
